# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Agent_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Company')),
            ],
        ),
        migrations.RenameModel(
            old_name='RelationLog',
            new_name='RelationLogHistory',
        ),
    ]
