# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20170725_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='avatar',
            field=models.ImageField(blank=True, default='logos/anonymous.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='logos/anonymous.png', null=True, upload_to=''),
        ),
    ]
