# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20170725_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Image',
            new_name='Company_Image',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Name',
            new_name='Company_Name',
        ),
    ]
