# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20170728_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='ag_nm',
        ),
        migrations.RemoveField(
            model_name='log',
            name='custo_id',
        ),
        migrations.AddField(
            model_name='log',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Agent'),
        ),
        migrations.AddField(
            model_name='log',
            name='cust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
    ]
